# Generated by Django 3.0.7 on 2021-04-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iaso', '0085_merge_20210415_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('EPID', models.TextField(blank=True, null=True)),
                ('OBR_name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onset_date', models.DateTimeField(blank=True, null=True)),
                ('cVDPV_notification_date', models.DateTimeField(blank=True, null=True)),
                ('three_level_call_date', models.DateTimeField(blank=True, null=True)),
                ('PV_notification_date', models.DateTimeField(blank=True, null=True)),
                ('virus', models.CharField(max_length=100)),
                ('vaccine', models.CharField(max_length=100)),
                ('detection_status', models.CharField(max_length=100)),
                ('reponsible', models.CharField(max_length=100)),
                ('cVDPV2_notification_date', models.DateTimeField(blank=True, null=True)),
                ('PV2_notification_date', models.DateTimeField(blank=True, null=True)),
                ('initial_ou', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iaso.OrgUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
